### ISSUE TITLE
NumPy 2 support

### ISSUE THREAD

**Issue by Hellseher** [dkogan/numpysane#3]
Hi,

Does numpysane support NumPy 2+?

When I try to build with NumPy  2.4.6 I've got the following build error:

```
./test/genpywrap.py > test/testlib_pywrap_GENERATED.c
gcc -g -Wno-missing-field-initializers -fno-strict-overflow -Wsign-compare -DNDEBUG -g -Wall -fno-semantic-interposition -fPIC -I/gnu/store/rh3vyrap1hswvgn122i7n7p5yba2spid-python-3.12.12/include/python3.12 -I/gnu/store/wjcng20g52vmlfc85c51275dfcnxyfkp-python-numpy-2.4.6/lib/python3.12//site-packages/numpy/core/include -Wno-cast-function-type   -c -o test/testlib_pywrap_GENERATED.o test/testlib_pywrap_GENERATED.c
test/testlib_pywrap_GENERATED.c:24:10: fatal error: numpy/arrayobject.h: No such file or directory
   24 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: test/testlib_pywrap_GENERATED.o] Error 1

```

Thanks.

**Comment by dkogan** [comment]
Hi. numpysane supports numpy2, and has for a long time. There's something different about your numpy install compared to other installs I've seen. The build uses `pkg-config --cflags-only-I numpy` to get the numpy header path. This works for you: your build ends up with `-I/gnu/store/wjcng20g52vmlfc85c51275dfcnxyfkp-python-numpy-2.4.6/lib/python3.12//site-packages/numpy/core/include` which, presumably, is what that returns. This path is supposed to have `numpy/arrayobject.h` in it, but I guess it does not? What do you see?

**Comment by Hellseher** [comment]
Hi,

There was a change between NumPy 1 and 2 for allocation of `include` directory.
v2.4.6 https://github.com/numpy/numpy/tree/v2.4.6/numpy/_core/include/numpy
v1.26.4https://github.com/numpy/numpy/tree/v1.26.4/numpy/core/include/numpy

Now it is fixed on our end by swamping search path from `core` to `_core`.

Thanks.

**Comment by dkogan** [comment]
Hi. Glad you figured it out. It looks like your numpy installation has a bug: the file lives in `.../_core/...` but `pkg-config` gave you `.../core/...`. If you can report this to the maintainer of your numpy package, that would be really great. Thanks

**Comment by Hellseher** [comment]
Hi,

This would be interesting case as I'm a maintainer of some Python related collection in Guix NumPy is part of it ;-) 
Comparing 1.26.4 and 2.4.6 the source structure changed dramatically, especially `include` migrated from core to _core directory, `numpy/_core/src` contains git sub-module which must be packaged separately, but it's a subject for anther story.

**Comment by dkogan** [comment]
Glad I complained to the right person :) Thanks for maintaining that.
